### ISSUE TITLE
关于「空容器」推荐PERK错误的BUG

### ISSUE THREAD

**Issue by Pcodcsja** [YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese#1]
在DIM中使用您的愿望清单在「空容器」这把枪中有BUG，您推荐的perk组合为斩首+自填，但是在DIM中会识别错误。我不确定是DIM的问题还是您的愿望清单有BUG，下面是详细的截图展示。如果条件允许的话，希望您能亲自测试一下，万分感激！
![Clip_2024-05-13_04-52-58](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/66547114/f7b2417c-e72a-4735-aad9-79da3658629d)

![Clip_2024-05-13_04-52-43](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/66547114/b72de1cd-8c13-471c-82c4-d8a7133ccf66)

![Clip_2024-05-13_04-53-26](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/66547114/0b681c57-0168-4763-ab87-0ce01bbce035)

![Clip_2024-05-13_04-53-36](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/66547114/52a70264-2120-4ce9-8fb9-ec5df7f4a1c0)
![Clip_2024-05-13_04-53-44](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/66547114/eb735d4f-befa-4b15-9466-5b73a66736d2)
![Clip_2024-05-13_04-53-54](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/66547114/6ee73612-b4de-4722-9923-e07f0721b675)

**Comment by YeSongYun** [comment]
很抱歉，这当然是我的错误，我在推荐列表里面填错perk序号了，尴尬ing，已经修改，感谢指正（b站狗头表情，需要脑部）

**Comment by YeSongYun** [comment]
很抱歉，这是我的错误，我在推荐perk中写错perk序号了，这真是糟糕的错误，这可能使得部分小伙伴错误的分解掉武器，呜呜，感谢大佬的指正，已经修改！
![未命名文件(1)](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/168858821/86be8d4c-e4a6-4328-95a4-03011a036b8d)

**Comment by YeSongYun** [comment]
很抱歉，这是我的错误，我在推荐perk中写错perk序号了，这真是糟糕的错误，这可能使得部分小伙伴错误的分解掉武器，呜呜，感谢大佬的指正，已经修改！
![微信图片_20240513050715](https://github.com/YeSongYun/DIM-wish-list-for-YeSongYun-for-Chinese/assets/168858821/65ea3867-6b05-4e01-b098-4faca7e96946)

**Comment by YeSongYun** [comment]
#
